### ISSUE TITLE
Example on sending messages to the chat?

### ISSUE THREAD

**Issue by ghost** [lookapanda/hitbox-chat-lib#2]
Would it be possible to put an example on how I could use this to allow a bot to put a message in the chat?

**Comment by Ponjimon** [comment]
https://github.com/lookapanda/hitbox-chat-lib/blob/master/demo/app.js#L10
Check the example.

It's not directly in there, but the channel object has the method `sendMessage()`

Example: 

``` javascript
channel.sendMessage('some text', '#abcdef');
```

**Comment by ghost** [comment]
But would it be possible to use channel.sendMessage outside the client area, for example if I call another method within it and use it within that method

Edit: turns out my problem wasn't with the sendMessage() line
